// lib/core/localization/app_localizations.dart
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'es_MX': {
      // México (Nativo)
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': 'Vamonos!!!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Genial!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que quieres cerrar sesión?',
      // Autenticación
      'welcome': 'Bienvenido',
      'discover_places': 'Descubre lugares increíbles cerca de ti',
      'email': 'Correo',
      'password': 'Contraseña',
      'username': 'Usuario',
      'username_optional': 'Nombre de usuario (opcional)',
      'login': 'Iniciar Sesión',
      'register': 'Registrarse',
      'or': 'O',
      'continue_with_google': 'Continuar con Google',
      'continue_with_apple': 'Continuar con Apple',
      'fill_all_fields': 'Por favor completa todos los campos',
      'redirecting_google': 'Redirigiendo a Google...',
      'invalid_credentials': '❌ Credenciales inválidas',
      'email_not_confirmed': '📧 Por favor confirma tu correo',
      'invalid_email': '❌ Correo inválido',
      'user_already_exists': '👤 Usuario ya registrado',
      'password_too_short': '🔐 Contraseña muy corta (mín 6 caracteres)',
      'weak_password': '🔐 Contraseña débil, usa números y caracteres especiales',
      'network_error': '📶 Error de conexión',
      // Perfil
      'edit_profile': 'Editar Perfil',
      'upload_photo': 'Subir Foto',
      'change_photo': 'Cambiar Foto',
      'description': 'Descripción',
      'edit_description': 'Editar descripción',
      'save_changes': 'Guardar Cambios',
      'profile_updated': 'Perfil actualizado correctamente',
      'error_loading_profile': 'Error al cargar perfil',
      'error_updating': 'Error al actualizar',
      'badges': 'Medallas',
      'no_badges': 'Sin medallas aún',
      // Historial
      'visited_places': 'Lugares Visitados',
      'pending_places': 'Lugares Pendientes',
      'no_visited': 'Sin lugares visitados aún',
      'no_pending': 'Sin lugares pendientes',
      'visit_date': 'Fecha de visita',
      'recommended_on': 'Recomendado el',
      'open_maps': 'Abrir en Maps',
      // Premium
      'premium': 'Premium',
      'go_premium': 'Hazte Premium',
      'premium_benefits': 'Beneficios Premium',
      // Favoritos
      'no_favorites': 'Sin favoritos aún',
      // Amigos
      'no_friends': 'Sin amigos aún',
      'add_friend': 'Agregar Amigo',
      // Detalles de lugar
      'rating': 'Calificación',
      'address': 'Dirección',
      'phone': 'Teléfono',
      'website': 'Sitio web',
      'hours': 'Horario',
      'open_now': 'Abierto ahora',
      'closed': 'Cerrado',
      'show_on_map': 'Ver en mapa',
      'distance': 'Distancia',
      'price_level': 'Nivel de precios',
      'rating_count': 'opiniones',
      // Logros
      'locked': 'Bloqueado',
      'progress': 'Progreso',
      'complete': 'Completado',
      'earned_on': 'Obtenido el',
      // Ranking
      'top_explorers': 'Top Exploradores',
      'rank': 'Rango',
      'level': 'Nivel',
      'experience': 'Experiencia',
      // Ajustes adicionales
      'notifications': 'Notificaciones',
      'location_permission': 'Permiso de ubicación',
      'about': 'Acerca de',
      'version': 'Versión',
      'privacy_policy': 'Política de privacidad',
      'terms': 'Términos y condiciones',
      // Errores
      'location_denied': 'Permiso de ubicación denegado',
      'no_connection': 'Sin conexión a internet',
      'something_wrong': 'Algo salió mal',
    },
    'es_ES': {
      // España
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Vamos!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se han encontrado resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Genial!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya he visitado este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que quieres cerrar sesión?',
    },
    'es_AR': {
      // Argentina
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Dale!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentá de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Genial!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones todavía',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Estás seguro que querés cerrar sesión?',
    },
    'es_CL': {
      // Chile
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Vamo!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Bacán!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que querí cerrar sesión?',
    },
    'es_CO': {
      // Colombia
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Listo pues!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Chevere!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que querés cerrar sesión?',
    },
    'es_PE': {
      // Perú
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Vamos pues!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Genial!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que quieres cerrar sesión?',
    },
    'es_VE': {
      // Venezuela
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Dale pues!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Chévere!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que quieres cerrar sesión?',
    },
    'en_US': {
      // English
      'app_title': 'Where Are We Going?',
      'explore': 'Explore',
      'history': 'History',
      'favorites': 'Favorites',
      'friends': 'Friends',
      'ranking': 'Ranking',
      'profile': 'Profile',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'dark_theme': 'Dark Theme',
      'light_theme': 'Light Theme',
      'current_location': 'Current location',
      'lets_go': 'Let\'s go!',
      'filters': 'Filters',
      'search': 'Search',
      'close': 'Close',
      'save': 'Save',
      'cancel': 'Cancel',
      'accept': 'Accept',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'no_results': 'No results found',
      'try_again': 'Try again',
      'achievements': 'Achievements',
      'my_achievements': 'My Achievements',
      'view_achievements': 'View Achievements',
      'unlocked_achievement': 'ACHIEVEMENT UNLOCKED!',
      'great': 'Great!',
      'restaurant': 'Restaurant',
      'cafe': 'Cafe',
      'bar': 'Bar',
      'place_type': 'Place type',
      'radius': 'Search radius',
      'km': 'km',
      'visited': 'Visited',
      'mark_as_visited': 'I\'ve visited this place',
      'add_review': 'Write review',
      'reviews': 'Reviews',
      'no_reviews': 'No reviews yet',
      'points': 'Points',
      'logout': 'Logout',
      'confirm_logout': 'Are you sure you want to logout?',
      // Autenticación
      'welcome': 'Welcome',
      'discover_places': 'Discover amazing places near you',
      'email': 'Email',
      'password': 'Password',
      'username': 'Username',
      'username_optional': 'Username (optional)',
      'login': 'Login',
      'register': 'Register',
      'or': 'Or',
      'continue_with_google': 'Continue with Google',
      'continue_with_apple': 'Continue with Apple',
      'fill_all_fields': 'Please fill all fields',
      'redirecting_google': 'Redirecting to Google...',
      'invalid_credentials': '❌ Invalid credentials',
      'email_not_confirmed': '📧 Please confirm your email',
      'invalid_email': '❌ Invalid email',
      'user_already_exists': '👤 User already registered',
      'password_too_short': '🔐 Password too short (min 6 characters)',
      'weak_password': '🔐 Weak password, use numbers and special characters',
      'network_error': '📶 Connection error',
      // Perfil
      'edit_profile': 'Edit Profile',
      'upload_photo': 'Upload Photo',
      'change_photo': 'Change Photo',
      'description': 'Description',
      'edit_description': 'Edit description',
      'save_changes': 'Save Changes',
      'profile_updated': 'Profile updated successfully',
      'error_loading_profile': 'Error loading profile',
      'error_updating': 'Error updating',
      'badges': 'Badges',
      'no_badges': 'No badges yet',
      // Historial
      'visited_places': 'Visited Places',
      'pending_places': 'Pending Places',
      'no_visited': 'No places visited yet',
      'no_pending': 'No pending places',
      'visit_date': 'Visit date',
      'recommended_on': 'Recommended on',
      'open_maps': 'Open in Maps',
      // Premium
      'premium': 'Premium',
      'go_premium': 'Go Premium',
      'premium_benefits': 'Premium Benefits',
      // Favoritos
      'no_favorites': 'No favorites yet',
      // Amigos
      'no_friends': 'No friends yet',
      'add_friend': 'Add Friend',
      // Detalles de lugar
      'rating': 'Rating',
      'address': 'Address',
      'phone': 'Phone',
      'website': 'Website',
      'hours': 'Hours',
      'open_now': 'Open now',
      'closed': 'Closed',
    },
  };

  String translate(String key) {
    final localeKey = '${locale.languageCode}_${locale.countryCode}';
    return _localizedValues[localeKey]?[key] ??
        _localizedValues['es_MX']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['es', 'en'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
