// lib/core/localization/app_localizations.dart
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'es_MX': {
      // México (Nativo)
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': 'Vamonos!!!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Genial!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que quieres cerrar sesión?',
    },
    'es_ES': {
      // España
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Vamos!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se han encontrado resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Genial!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya he visitado este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que quieres cerrar sesión?',
    },
    'es_AR': {
      // Argentina
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Dale!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentá de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Genial!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones todavía',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Estás seguro que querés cerrar sesión?',
    },
    'es_CL': {
      // Chile
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Vamo!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Bacán!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que querí cerrar sesión?',
    },
    'es_CO': {
      // Colombia
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Listo pues!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Chevere!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que querés cerrar sesión?',
    },
    'es_PE': {
      // Perú
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Vamos pues!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Genial!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que quieres cerrar sesión?',
    },
    'es_VE': {
      // Venezuela
      'app_title': '¿A Dónde Vamos?',
      'explore': 'Explorar',
      'history': 'Historial',
      'favorites': 'Favoritos',
      'friends': 'Amigos',
      'ranking': 'Ranking',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'current_location': 'Ubicación actual',
      'lets_go': '¡Dale pues!',
      'filters': 'Filtros',
      'search': 'Buscar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'error': 'Error',
      'success': 'Éxito',
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'try_again': 'Intentar de nuevo',
      'achievements': 'Logros',
      'my_achievements': 'Mis Logros',
      'view_achievements': 'Ver Logros',
      'unlocked_achievement': '¡LOGRO DESBLOQUEADO!',
      'great': '¡Chévere!',
      'restaurant': 'Restaurante',
      'cafe': 'Cafetería',
      'bar': 'Bar',
      'place_type': 'Tipo de lugar',
      'radius': 'Radio de búsqueda',
      'km': 'km',
      'visited': 'Visitado',
      'mark_as_visited': 'Ya visité este lugar',
      'add_review': 'Escribir opinión',
      'reviews': 'Opiniones',
      'no_reviews': 'Sin opiniones aún',
      'points': 'Puntos',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Seguro que quieres cerrar sesión?',
    },
    'en_US': {
      // English
      'app_title': 'Where Are We Going?',
      'explore': 'Explore',
      'history': 'History',
      'favorites': 'Favorites',
      'friends': 'Friends',
      'ranking': 'Ranking',
      'profile': 'Profile',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'dark_theme': 'Dark Theme',
      'light_theme': 'Light Theme',
      'current_location': 'Current location',
      'lets_go': 'Let\'s go!',
      'filters': 'Filters',
      'search': 'Search',
      'close': 'Close',
      'save': 'Save',
      'cancel': 'Cancel',
      'accept': 'Accept',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'no_results': 'No results found',
      'try_again': 'Try again',
      'achievements': 'Achievements',
      'my_achievements': 'My Achievements',
      'view_achievements': 'View Achievements',
      'unlocked_achievement': 'ACHIEVEMENT UNLOCKED!',
      'great': 'Great!',
      'restaurant': 'Restaurant',
      'cafe': 'Cafe',
      'bar': 'Bar',
      'place_type': 'Place type',
      'radius': 'Search radius',
      'km': 'km',
      'visited': 'Visited',
      'mark_as_visited': 'I\'ve visited this place',
      'add_review': 'Write review',
      'reviews': 'Reviews',
      'no_reviews': 'No reviews yet',
      'points': 'Points',
      'logout': 'Logout',
      'confirm_logout': 'Are you sure you want to logout?',
    },
  };

  String translate(String key) {
    final localeKey = '${locale.languageCode}_${locale.countryCode}';
    return _localizedValues[localeKey]?[key] ??
        _localizedValues['es_MX']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['es', 'en'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
